// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pilot} from '../models';
import {main} from '../models';

export function GetPilotConfig():Promise<pilot.PilotConfig>;

export function GetPilotLogs():Promise<Array<main.LogEntry>>;

export function GetPilotStatus():Promise<pilot.PilotStatus>;

export function InstallPilotHooks():Promise<void>;

export function SavePilotConfig(arg1:pilot.PilotConfig):Promise<void>;

export function UninstallPilotHooks():Promise<void>;
