// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPilotConfig() {
  return window['go']['main']['App']['GetPilotConfig']();
}

export function GetPilotStatus() {
  return window['go']['main']['App']['GetPilotStatus']();
}

export function InstallPilotHooks() {
  return window['go']['main']['App']['InstallPilotHooks']();
}

export function SavePilotConfig(arg1) {
  return window['go']['main']['App']['SavePilotConfig'](arg1);
}

export function StartPilotWrapper() {
  return window['go']['main']['App']['StartPilotWrapper']();
}

export function StopPilotWrapper() {
  return window['go']['main']['App']['StopPilotWrapper']();
}

export function UninstallPilotHooks() {
  return window['go']['main']['App']['UninstallPilotHooks']();
}
